/*
 * generated by Xtext
 */
package rs.demsys.rst.ui;

import rs.demsys.rst.ui.contentassist.RstProposalProvider;
import rs.demsys.rst.ui.highlighting.RstHighlightingCalculator;
import rs.demsys.rst.ui.highlighting.RstHighlightingConfiguration;
import rs.demsys.rst.ui.hyperlink.RstHyperlinkHelper;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.contentassist.ITemplateProposalProvider;
import org.eclipse.xtext.ui.editor.hyperlinking.IHyperlinkHelper;
import org.eclipse.xtext.ui.editor.model.XtextDocumentProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RstUiModule extends rs.demsys.rst.ui.AbstractRstUiModule {
	public RstUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration () {
        return RstHighlightingConfiguration.class;
    }
    
    public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator(){
        return RstHighlightingCalculator.class;
    }
    
    @Override
    public Class<? extends IHyperlinkHelper> bindIHyperlinkHelper() {
        return RstHyperlinkHelper.class;
    }
    
}
