/*
 * generated by Xtext
 */
package rs.demsys.rst.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BibUiModule extends rs.demsys.rst.ui.AbstractBibUiModule {
	public BibUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
